language: go
go:
   - master
install:
   - go get github.com/spf13/hugo
script:
   - hugo
deploy:
   local_dir: public    # hugo build output path
   repo: RulersOth.github.io  # target repo
   target_branch: master
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   email: jayay.byeun@gmail.com
   name: "RulersOth"
   on:
      branch: master
